sudo: required

services:
  - docker

env:
  global:
    - appUser="media"
    - appGroup="media"

install:
  - docker build --rm --no-cache -t cryptout/transmission ../transmission

script:
  - ./rundocker.sh
  - sleep 10
  - bats tests/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cryptout/transmission:latest;
    fi

notifications:
  email: false
